travis:
  secure:
    BINSTAR_TOKEN: kPWFBzizMS091sJW/NDMgrU87E7jFnX1pNsPDu11gQN40NRXqlbViClUn4SCGVFczxgAwxx6ei+TOGIKU3Mh4bGkZyOGSlqy32+8bxqxXqubyNYdmb1dwaWd8kWa1r29KcTPyhOoQKmqh6Hga0lLJvLh79VlhlM+TLMQWCGKq69Ia0emEi9LRyWnyIPikbWO+H83hmS6FsZb0Uz2z2GdnDlCH5MadSLu0wdMscBo0FoNeh53B58q1YEMQLzYF+MYmyKSoVL3I5LvBndzSnmY4Px1rTOs04Iv7fo2kPBNsHZ0zyTFOQYq/w/AbZQjiM/px2zKKFmH1uwpeJfDaF7h2I7HgfBn384DaOQMt0eWCJZMjONyeBpL7RqrUR35WycHFtJC4AAktxEkOcVvMU6cjD0h5gqX4tBXGvRf7RKg77uFNHVSr4sIxbh7SLI3Mv1C4wwJWI+Lyo4Z7iw9Sfj78FQ2vDVtgtF+v3ZZIoTjJ4P3oDZlNphwxGn7H+DNBBMu4PNpizQt6U5xFbFX+YKL853tvNAHUSztOgAP5sNzJzZTYdauOxVtqjHlajFpgmH6ZiMebX69TYtLb3bNx/hWfHQ/5GwI+W9D25jXMM8p2VzUmoTyZive0PoAlhNqIrUfOELV4CiO1BykWGNJFsehWv+0uDkDDdU2On2kxqup13E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
